### ISSUE TITLE
event.js 141

### ISSUE THREAD

**Issue by dmrathore** [JeremyBYU/modbus#2]
hello,
I am using the your package for my project and its working fine but recently i got this error-

events.js:141
 throw er; // Unhandled 'error' event
 ^
ResponseTimeoutError: No response was received from the slave in the specified time.
 at Transaction.handleTimeout (/media/rathore/mydata/project/inspinia_test/.meteor/local/isopacks/jeremybyu_mmodbus/npm/node_modules1/h5.modbus/lib/Transaction.js:452:20)
  at Timer.listOnTimeout (timers.js:92:15)

Can you help me with this error.

Thanks

**Comment by JeremyBYU** [comment]
Hey not sure what's going on. I used this project for a toy setup in my
garage and it was never on longer than 20 minutes. Looks like maybe my
module or h5 modbus forgot to catch a response time out error. I think I
remember my code somewhere catching errors, from h5 modbus. Maybe try
forking and try catching the errors? I won't be able to help you much more
than that.

On Jul 12, 2017 2:57 AM, "dmrathore" <notifications@github.com> wrote:

hello,
I am using the your package for my project and its working fine but
recently i got this error-

events.js:141
throw er; // Unhandled 'error' event
^
ResponseTimeoutError: No response was received from the slave in the
specified time.
at Transaction.handleTimeout (/media/rathore/mydata/
project/inspinia_test/.meteor/local/isopacks/jeremybyu_
mmodbus/npm/node_modules1/h5.modbus/lib/Transaction.js:452:20)
at Timer.listOnTimeout (timers.js:92:15)

Can you help me with this error.

Thanks

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/JeremyBYU/modbus/issues/2>, or mute the thread
